<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Framework\ShopIt.Framework.Core\ShopIt.Framework.Core.csproj" />
    <ProjectReference Include="..\..\Identity\ShopIt.Identity.Application.Contracts\ShopIt.Identity.Application.Contracts.csproj" />
    <ProjectReference Include="..\ShopIt.Tenancy.Domain\ShopIt.Tenancy.Domain.csproj" />
  </ItemGroup>

</Project>
