<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\ShopIt.Framework.Core\ShopIt.Framework.Core.csproj" />
    <ProjectReference Include="..\ShopIt.Framework.Domain\ShopIt.Framework.Domain.csproj" />
    <ProjectReference Include="..\ShopIt.Framework.Persistence\ShopIt.Framework.Persistence.csproj" />
  </ItemGroup>

</Project>
