<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\ShopIt.ServiceDefaults\ShopIt.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\Framework\ShopIt.Framework.Core\ShopIt.Framework.Core.csproj" />
    <ProjectReference Include="..\..\Identity\ShopIt.Identity.Persistence\ShopIt.Identity.Persistence.csproj" />
    <ProjectReference Include="..\..\Identity\ShopIt.Identity.Presentation\ShopIt.Identity.Presentation.csproj" />
  </ItemGroup>

</Project>
