@BaseUrl = https://localhost:7009

GET {{BaseUrl}}/weatherforecast/
Accept: application/json

###

### Create User
POST {{BaseUrl}}/users
Content-Type: application/json


{
    "username": "Mohammad",
    "email": "test@test.com"
}
###

### Get User by Id
GET {{BaseUrl}}/users/f3743d76-8fc1-4afd-b6b3-1b10051c56ae
###

### Assign User to Role
POST {{BaseUrl}}/users/roles
###
