<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Repositories/" />
    <Folder Include="UnitOfWork/" />
    <Folder Include="Outbox/" />
    <Folder Include="Inbox/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ShopIt.Framework.Core/ShopIt.Framework.Core.csproj" />
    <ProjectReference Include="../ShopIt.Framework.Domain/ShopIt.Framework.Domain.csproj" />
  </ItemGroup>

</Project>
